# Intro teórica

no voy a hacer todos los ejercicios ya que se las bases

1. en jupyter notebook hay 3 tipos de celdas:
    - de código
    - markdown
    - texto
    
    El entorno de ejecución en jupyter involucra a los elementos necesarios para ejecutar mi código, como el kernel, las bibliotecas y otras dependencias
    

1. en el código puedo poner !dir por ejemplo y otros comandos de mis SO

In [21]:
!pip show numpy

Name: numpy
Version: 1.24.3
Summary: Fundamental package for array computing in Python
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD-3-Clause
Location: C:\Users\Mateo\anaconda3\Lib\site-packages
Requires: 
Required-by: astropy, bokeh, Bottleneck, contourpy, daal4py, datasets, datashader, datashape, gensim, h5py, holoviews, hvplot, imagecodecs, imageio, imbalanced-learn, matplotlib, mkl-fft, mkl-random, numba, numexpr, pandas, patsy, pyarrow, pyerfa, PyWavelets, scikit-image, scikit-learn, scikit-surprise, scipy, seaborn, statsmodels, tables, tifffile, transformers, xarray


In [22]:
!pip show pandas

Name: pandas
Version: 2.0.3
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: 
Author: 
Author-email: The Pandas Development Team <pandas-dev@python.org>
License: BSD 3-Clause License

Copyright (c) 2008-2011, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team
All rights reserved.

Copyright (c) 2011-2023, Open source contributors.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote

In [23]:
!python --version

Python 3.11.5


# Repaso Python

In [1]:
#repaso python

#ej 2
lista1 = [1, 2, 3, 4]
lista2 = ['a', 'b', 'c', 'd']

#una tupla es una lista inmutable con elementos de diferentes tipos
for elemento1, elemento2 in zip(lista1, lista2): #con zip generamos una tupla, la cual tiene un elemento de cada lista en cada posición
    print(f"Elemento de lista1: {elemento1}, Elemento de lista2: {elemento2}")

Elemento de lista1: 1, Elemento de lista2: a
Elemento de lista1: 2, Elemento de lista2: b
Elemento de lista1: 3, Elemento de lista2: c
Elemento de lista1: 4, Elemento de lista2: d


In [2]:
#ej 3
lista3 = [1, 1, 2, 3, 4]
for elemento in set(lista3): #set hace que no tengamos elementos repetidos
    print(f"elemento {elemento}")
#set crea un conjunto, el cual es una estructura en python que no contiene repetidos, es mutable, no hay un órden y se pueden aplicar funciones de intersección y similares

elemento 1
elemento 2
elemento 3
elemento 4


In [5]:
#ej 4
import math

def calcularDistancia(punto1, punto2):
    catetoA = abs(punto1[0] - punto2[0])
    catetoB = abs(punto1[1] - punto2[1])
    hipotenusa = math.sqrt(catetoA**2 + catetoB**2)
    return hipotenusa
    
punto1 = [10, 4] # (x, y)
punto2 = [11, 5] #a 2^0.5 de distancia
distancia = calcularDistancia(punto1, punto2)
print(f"la distancia entre los puntos es de {distancia} unidades")

la distancia entre los puntos es de 1.4142135623730951 unidades


In [6]:
#ej 5
#los slices son partes de una lista: lista[inicio:fin:paso] -> incluye el inicio, no incluye el fin
#Si no aclaro el inicio va desde el principio, si no aclaro el fin va hasta el final, si no aclaro el paso entonces es de a 1

mi_lista = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
slice_1 = mi_lista[2:7]
print("Slice 1 (mi_lista[2:7]):", slice_1)  # Salida: [2, 3, 4, 5, 6]
slice_2 = mi_lista[:5]
print("Slice 2 (mi_lista[:5]):", slice_2)  # Salida: [0, 1, 2, 3, 4]
slice_3 = mi_lista[5:]
print("Slice 3 (mi_lista[5:]):", slice_3)  # Salida: [5, 6, 7, 8, 9]
slice_4 = mi_lista[1:8:2]
print("Slice 4 (mi_lista[1:8:2]):", slice_4)  # Salida: [1, 3, 5, 7]
slice_5 = mi_lista[::-1]
print("Slice 5 (mi_lista[::-1]):", slice_5)  # Salida: [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
slice_6 = mi_lista[-4:-1]
print("Slice 6 (mi_lista[-4:-1]):", slice_6)  # Salida: [6, 7, 8]
slice_7 = mi_lista[:]
print("Slice 7 (mi_lista[:]):", slice_7)  # Salida: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Slice 1 (mi_lista[2:7]): [2, 3, 4, 5, 6]
Slice 2 (mi_lista[:5]): [0, 1, 2, 3, 4]
Slice 3 (mi_lista[5:]): [5, 6, 7, 8, 9]
Slice 4 (mi_lista[1:8:2]): [1, 3, 5, 7]
Slice 5 (mi_lista[::-1]): [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
Slice 6 (mi_lista[-4:-1]): [6, 7, 8]
Slice 7 (mi_lista[:]): [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


# Biblioteca Numpy
numpy proporciona una interfaz eficiente y flexible para trabajar con estas estructuras de datos

In [11]:
#ej 1 -> creación de vectores

import numpy as np

# Creación de un vector con elementos especificados
vector = np.array([1, 2, 3, 4, 5])
print("Vector:", vector)

# Creación de un vector de ceros
vector_ceros = np.zeros(5)
print("Vector de ceros:", vector_ceros)

# Creación de un vector de unos
vector_unos = np.ones(5)
print("Vector de unos:", vector_unos)

# Creación de un vector con valores en un rango específico
vector_rango = np.arange(10, 20) #-> no es random, es de paso 1
print("Vector con rango:", vector_rango)

# Creación de un vector con valores equiespaciados
vector_linspace = np.linspace(0, 1, 5)
print("Vector equiespaciado:", vector_linspace)

vector_aleatorio_uniforme = np.random.rand(5)
print("Vector aleatorio (uniforme [0, 1)):", vector_aleatorio_uniforme)

Vector: [1 2 3 4 5]
Vector de ceros: [0. 0. 0. 0. 0.]
Vector de unos: [1. 1. 1. 1. 1.]
Vector con rango: [10 11 12 13 14 15 16 17 18 19]
Vector equiespaciado: [0.   0.25 0.5  0.75 1.  ]
Vector aleatorio (uniforme [0, 1)): [0.7723639  0.50607924 0.2279858  0.07987642 0.26616018]


In [8]:
#ej 1-> creación de matrices

# Creación de una matriz 2x3 con elementos especificados
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print("Matriz:\n", matriz)

# Creación de una matriz de ceros 3x3
matriz_ceros = np.zeros((3, 3))
print("Matriz de ceros:\n", matriz_ceros)

# Creación de una matriz de unos 2x4
matriz_unos = np.ones((2, 4))
print("Matriz de unos:\n", matriz_unos)

# Creación de una matriz identidad 3x3
matriz_identidad = np.eye(3)
print("Matriz identidad:\n", matriz_identidad)

# Creación de una matriz con valores aleatorios
matriz_aleatoria = np.random.rand(2, 3)
print("Matriz aleatoria:\n", matriz_aleatoria)


Matriz:
 [[1 2 3]
 [4 5 6]]
Matriz de ceros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Matriz de unos:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Matriz identidad:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Matriz aleatoria:
 [[0.1223772  0.19845291 0.37137352]
 [0.44859172 0.0890108  0.78778734]]


In [12]:
#ej 1 -> creación de tensores = arreglos de 3 dimensiones o más

# Creación de un tensor 3x3x2 con elementos especificados
tensor = np.array([[[1, 2], [3, 4], [5, 6]], 
                   [[7, 8], [9, 10], [11, 12]],
                   [[13, 14], [15, 16], [17, 18]]])
print("Tensor:\n", tensor)

# Creación de un tensor 2x2x3 de ceros
tensor_ceros = np.zeros((2, 2, 3))
print("Tensor de ceros:\n", tensor_ceros)

# Creación de un tensor 3x3x3 de unos
tensor_unos = np.ones((3, 3, 3))
print("Tensor de unos:\n", tensor_unos)

# Creación de un tensor 3x2x4 con valores aleatorios
tensor_aleatorio = np.random.rand(3, 2, 4)
print("Tensor aleatorio:\n", tensor_aleatorio)


Tensor:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
Tensor de ceros:
 [[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
Tensor de unos:
 [[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
Tensor aleatorio:
 [[[0.76396752 0.62498137 0.56499816 0.74759495]
  [0.70986551 0.39653047 0.51999016 0.04921578]]

 [[0.48725338 0.99468166 0.01914023 0.95429674]
  [0.76480754 0.45006054 0.2085931  0.89309753]]

 [[0.1903634  0.97894912 0.31076337 0.05307265]
  [0.35705571 0.63036012 0.72275205 0.76169802]]]


In [20]:
#ej 1 -> uso de diferentes constructores para arreglos:

#array() -> carga los datos desde una lista
lista = [1, 2, 3, 4, 5]
array_desde_lista = np.array(lista)
print("array():", array_desde_lista)

#empty -> inicializa con basura
array_vacio = np.empty((3, 3))
print("Array vacío:\n", array_vacio)

#full -> carga todo con el mismo valor
array_lleno = np.full((2, 3), 7)
print("Array lleno con 7:\n", array_lleno)

#zeros() -> full de 0
array_ceros = np.zeros((2, 4))
print("Array de ceros:\n", array_ceros)

#ones() -> full de 1
array_unos = np.ones((3, 2))
print("Array de unos:\n", array_unos)

#identity -> matriz identidad
matriz_identidad = np.identity(4)
print("Matriz identidad:\n", matriz_identidad)

array(): [1 2 3 4 5]
Array vacío:
 [[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [1.78019082e-306 1.89146896e-307 7.56571288e-307]
 [3.11525958e-307 1.24610723e-306 0.00000000e+000]]
Array lleno con 7:
 [[7 7 7]
 [7 7 7]]
Array de ceros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array de unos:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Matriz identidad:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


numpy puede generar arreglos de muchos tipos de datos, donde no solo indico si es integer por ejemplo, sinó que también puedo elegir entre cuantos bytes vaya a usar la variable. Me permite tener datos de primitivos y objetos

El tipo de datos que se utiliza por defecto al crear un array en numpy depende de los datos proporcionados:

Si se proporcionan números enteros, el tipo por defecto es int64 en sistemas de 64 bits y int32 en sistemas de 32 bits.
Si se proporcionan números flotantes, el tipo por defecto es float64.
Si se proporcionan números complejos, el tipo por defecto es complex128.