# Intro teórica

no voy a hacer todos los ejercicios ya que se las bases

1. en jupyter notebook hay 3 tipos de celdas:
    - de código
    - markdown
    - texto
    
    El entorno de ejecución en jupyter involucra a los elementos necesarios para ejecutar mi código, como el kernel, las bibliotecas y otras dependencias
    

1. en el código puedo poner !dir por ejemplo y otros comandos de mis SO

In [21]:
!pip show numpy

Name: numpy
Version: 1.24.3
Summary: Fundamental package for array computing in Python
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD-3-Clause
Location: C:\Users\Mateo\anaconda3\Lib\site-packages
Requires: 
Required-by: astropy, bokeh, Bottleneck, contourpy, daal4py, datasets, datashader, datashape, gensim, h5py, holoviews, hvplot, imagecodecs, imageio, imbalanced-learn, matplotlib, mkl-fft, mkl-random, numba, numexpr, pandas, patsy, pyarrow, pyerfa, PyWavelets, scikit-image, scikit-learn, scikit-surprise, scipy, seaborn, statsmodels, tables, tifffile, transformers, xarray


In [22]:
!pip show pandas

Name: pandas
Version: 2.0.3
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: 
Author: 
Author-email: The Pandas Development Team <pandas-dev@python.org>
License: BSD 3-Clause License

Copyright (c) 2008-2011, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team
All rights reserved.

Copyright (c) 2011-2023, Open source contributors.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote

In [23]:
!python --version

Python 3.11.5


# Repaso Python

In [1]:
#repaso python

#ej 2
lista1 = [1, 2, 3, 4]
lista2 = ['a', 'b', 'c', 'd']

#una tupla es una lista inmutable con elementos de diferentes tipos
for elemento1, elemento2 in zip(lista1, lista2): #con zip generamos una tupla, la cual tiene un elemento de cada lista en cada posición
    print(f"Elemento de lista1: {elemento1}, Elemento de lista2: {elemento2}")

Elemento de lista1: 1, Elemento de lista2: a
Elemento de lista1: 2, Elemento de lista2: b
Elemento de lista1: 3, Elemento de lista2: c
Elemento de lista1: 4, Elemento de lista2: d


In [2]:
#ej 3
lista3 = [1, 1, 2, 3, 4]
for elemento in set(lista3): #set hace que no tengamos elementos repetidos
    print(f"elemento {elemento}")
#set crea un conjunto, el cual es una estructura en python que no contiene repetidos, es mutable, no hay un órden y se pueden aplicar funciones de intersección y similares

elemento 1
elemento 2
elemento 3
elemento 4


In [5]:
#ej 4
import math

def calcularDistancia(punto1, punto2):
    catetoA = abs(punto1[0] - punto2[0])
    catetoB = abs(punto1[1] - punto2[1])
    hipotenusa = math.sqrt(catetoA**2 + catetoB**2)
    return hipotenusa
    
punto1 = [10, 4] # (x, y)
punto2 = [11, 5] #a 2^0.5 de distancia
distancia = calcularDistancia(punto1, punto2)
print(f"la distancia entre los puntos es de {distancia} unidades")

la distancia entre los puntos es de 1.4142135623730951 unidades


In [6]:
#ej 5
#los slices son partes de una lista: lista[inicio:fin:paso] -> incluye el inicio, no incluye el fin
#Si no aclaro el inicio va desde el principio, si no aclaro el fin va hasta el final, si no aclaro el paso entonces es de a 1

mi_lista = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
slice_1 = mi_lista[2:7]
print("Slice 1 (mi_lista[2:7]):", slice_1)  # Salida: [2, 3, 4, 5, 6]
slice_2 = mi_lista[:5]
print("Slice 2 (mi_lista[:5]):", slice_2)  # Salida: [0, 1, 2, 3, 4]
slice_3 = mi_lista[5:]
print("Slice 3 (mi_lista[5:]):", slice_3)  # Salida: [5, 6, 7, 8, 9]
slice_4 = mi_lista[1:8:2]
print("Slice 4 (mi_lista[1:8:2]):", slice_4)  # Salida: [1, 3, 5, 7]
slice_5 = mi_lista[::-1]
print("Slice 5 (mi_lista[::-1]):", slice_5)  # Salida: [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
slice_6 = mi_lista[-4:-1]
print("Slice 6 (mi_lista[-4:-1]):", slice_6)  # Salida: [6, 7, 8]
slice_7 = mi_lista[:]
print("Slice 7 (mi_lista[:]):", slice_7)  # Salida: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Slice 1 (mi_lista[2:7]): [2, 3, 4, 5, 6]
Slice 2 (mi_lista[:5]): [0, 1, 2, 3, 4]
Slice 3 (mi_lista[5:]): [5, 6, 7, 8, 9]
Slice 4 (mi_lista[1:8:2]): [1, 3, 5, 7]
Slice 5 (mi_lista[::-1]): [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
Slice 6 (mi_lista[-4:-1]): [6, 7, 8]
Slice 7 (mi_lista[:]): [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


# Biblioteca Numpy
numpy proporciona una interfaz eficiente y flexible para trabajar con estas estructuras de datos

In [2]:
#ej 1 -> creación de vectores

import numpy as np

# Creación de un vector con elementos especificados
vector = np.array([1, 2, 3, 4, 5])
print("Vector:", vector)

# Creación de un vector de ceros
vector_ceros = np.zeros(5)
print("Vector de ceros:", vector_ceros)

# Creación de un vector de unos
vector_unos = np.ones(5)
print("Vector de unos:", vector_unos)

# Creación de un vector con valores en un rango específico
vector_rango = np.arange(10, 20) #-> no es random, es de paso 1
print("Vector con rango:", vector_rango)

# Creación de un vector con valores equiespaciados
vector_linspace = np.linspace(0, 1, 5)
print("Vector equiespaciado:", vector_linspace)

vector_aleatorio_uniforme = np.random.rand(5)
print("Vector aleatorio (uniforme [0, 1)):", vector_aleatorio_uniforme)

Vector: [1 2 3 4 5]
Vector de ceros: [0. 0. 0. 0. 0.]
Vector de unos: [1. 1. 1. 1. 1.]
Vector con rango: [10 11 12 13 14 15 16 17 18 19]
Vector equiespaciado: [0.   0.25 0.5  0.75 1.  ]
Vector aleatorio (uniforme [0, 1)): [0.51445604 0.09240355 0.36335814 0.10796603 0.02756372]


In [3]:
#ej 1-> creación de matrices

# Creación de una matriz 2x3 con elementos especificados
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print("Matriz:\n", matriz)

# Creación de una matriz de ceros 3x3
matriz_ceros = np.zeros((3, 3))
print("Matriz de ceros:\n", matriz_ceros)

# Creación de una matriz de unos 2x4
matriz_unos = np.ones((2, 4))
print("Matriz de unos:\n", matriz_unos)

# Creación de una matriz identidad 3x3
matriz_identidad = np.eye(3)
print("Matriz identidad:\n", matriz_identidad)

# Creación de una matriz con valores aleatorios
matriz_aleatoria = np.random.rand(2, 3)
print("Matriz aleatoria:\n", matriz_aleatoria)


Matriz:
 [[1 2 3]
 [4 5 6]]
Matriz de ceros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Matriz de unos:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Matriz identidad:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Matriz aleatoria:
 [[0.16850768 0.43452783 0.91731016]
 [0.17231996 0.73627026 0.5252198 ]]


In [4]:
#ej 1 -> creación de tensores = arreglos de 3 dimensiones o más

# Creación de un tensor 3x3x2 con elementos especificados
tensor = np.array([[[1, 2], [3, 4], [5, 6]], 
                   [[7, 8], [9, 10], [11, 12]],
                   [[13, 14], [15, 16], [17, 18]]])
print("Tensor:\n", tensor)

# Creación de un tensor 2x2x3 de ceros
tensor_ceros = np.zeros((2, 2, 3))
print("Tensor de ceros:\n", tensor_ceros)

# Creación de un tensor 3x3x3 de unos
tensor_unos = np.ones((3, 3, 3))
print("Tensor de unos:\n", tensor_unos)

# Creación de un tensor 3x2x4 con valores aleatorios
tensor_aleatorio = np.random.rand(3, 2, 4)
print("Tensor aleatorio:\n", tensor_aleatorio)


Tensor:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
Tensor de ceros:
 [[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
Tensor de unos:
 [[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
Tensor aleatorio:
 [[[0.41649413 0.73160607 0.49671144 0.69676175]
  [0.64888687 0.05922598 0.68992904 0.00780348]]

 [[0.02985069 0.92995878 0.90858873 0.79034449]
  [0.54273989 0.84271364 0.3648561  0.4284231 ]]

 [[0.33466244 0.32271181 0.64822336 0.85282642]
  [0.51598636 0.25437135 0.63529058 0.24017639]]]


In [5]:
#ej 1 -> uso de diferentes constructores para arreglos:

#array() -> carga los datos desde una lista
lista = [1, 2, 3, 4, 5]
array_desde_lista = np.array(lista)
print("array():", array_desde_lista)

#empty -> inicializa con basura
array_vacio = np.empty((3, 3))
print("Array vacío:\n", array_vacio)

#full -> carga todo con el mismo valor
array_lleno = np.full((2, 3), 7)
print("Array lleno con 7:\n", array_lleno)

#zeros() -> full de 0
array_ceros = np.zeros((2, 4))
print("Array de ceros:\n", array_ceros)

#ones() -> full de 1
array_unos = np.ones((3, 2))
print("Array de unos:\n", array_unos)

#identity -> matriz identidad
matriz_identidad = np.identity(4)
print("Matriz identidad:\n", matriz_identidad)

array(): [1 2 3 4 5]
Array vacío:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array lleno con 7:
 [[7 7 7]
 [7 7 7]]
Array de ceros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array de unos:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Matriz identidad:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


numpy puede generar arreglos de muchos tipos de datos, donde no solo indico si es integer por ejemplo, sinó que también puedo elegir entre cuantos bytes vaya a usar la variable. Me permite tener datos de primitivos y objetos

El tipo de datos que se utiliza por defecto al crear un array en numpy depende de los datos proporcionados:

Si se proporcionan números enteros, el tipo por defecto es int64 en sistemas de 64 bits y int32 en sistemas de 32 bits.
Si se proporcionan números flotantes, el tipo por defecto es float64.
Si se proporcionan números complejos, el tipo por defecto es complex128.

In [6]:
#ej 2

a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

#dice las dimensiones del arreglo
print("Shape:", a.shape)
# Salida: Shape: (3, 4)

#dice la longitud de la lista principal, es lo mismo que el primer número de shape
print("Len:", len(a))
# Salida: Len: 3

#dimensión
print("NDim:", a.ndim)
# Salida: NDim: 2

#cantidad de elementos individuales
print("Size:", a.size)
# Salida: Size: 12

Shape: (3, 4)
Len: 3
NDim: 2
Size: 12


los arreglos de numpy pueden tener muchos tipos de datos, inclyuyendo complejos (números con parte real e imaginaria), objetos, primitivos, etc

Tipo de Dato por Defecto
Por defecto: 
- float64 si hay números decimales
- int64 si todos los valores son enteros
- Si proporcionas una lista de strings, el tipo será str
- etc

In [ ]:
#formas de generar números random con numpy según diferentes distribucione estadísticas:

#uniforme (flotantes)
arr = np.random.rand(3, 4)#números en [0,1)
arr = np.random.random((3, 4)) #la diferencia es que enviamos un solo parámetro que es una tupla, números en [0,1)
arr = np.random.uniform(10, 20, size=(3, 4))#elijo el rango de posibles valores
arr = np.random.choice([10, 20, 30, 40], size=(3, 4))#le doy la lista de posibles elecciones, puedo especificar si es con reemplazo o no

#normal estándar 
arr = np.random.randn(3, 4) #(media 0, desviación estándar 1)
arr = np.random.normal(loc=0, scale=1, size=(3, 4)) #permite personalizar la media (loc) y la desviación estándar (scale).

#uniforme discreta (enteros)
arr = np.random.randint(1, 10, size=(3, 4))



In [ ]:
#ej 3
#operaciones a lo largo de diferentes ejes=dimensiones -> la especifico con axis
#axis 0 es fila y axis 1 es columna cuando tratamos matrices

#suma
arr = np.array([[1, 2, 3], [4, 5, 6]])
total_sum = np.sum(arr)#21
row_sum = np.sum(arr, axis=0)#[5 7 9]
col_sum = np.sum(arr, axis=1)#[ 6 15]

#mínimo
arr = np.array([[7, 2, 3], [4, 9, 6]])
min_value = np.min(arr)#2
min_row = np.min(arr, axis=0)#[4 2 3]
min_col = np.min(arr, axis=1)#[2 4]

#maximo
arr = np.array([[1, 8, 3], [4, 5, 10]])
max_value = np.max(arr) #10
max_row = np.max(arr, axis=0)#[4 8 10]
max_col = np.max(arr, axis=1)#[8 10]

#promedio=mean
arr = np.array([[1, 2, 3], [4, 5, 6]])
mean_value = np.mean(arr)#3.5
mean_row = np.mean(arr, axis=0)#[2.5 3.5 4.5]
mean_col = np.mean(arr, axis=1)#[2. 5.]

#desviación estándar = std
arr = np.array([[1, 2, 3], [4, 5, 6]])
std_dev = np.std(arr)#1.707825127659933
std_row = np.std(arr, axis=0)#[1.5 1.5 1.5]
std_col = np.std(arr, axis=1)#[0.81649658 0.81649658]

In [ ]:
#ej 4 -> manipular arreglos individuales

#agregar al final
arr = np.array([1, 2, 3])
arr_appended = np.append(arr, [4, 5]) #tmb puedo indicar el axis=eje=dimensión

arr = np.array([[1, 2], [3, 4]])
arr_appended = np.append(arr, [[5], [6]], axis=1)
# [[1 2 5]
#  [3 4 6]]

#agregar en una posición específica -> el 2do parámetro es la posición ahora
arr = np.array([[1, 2], [3, 4]])
arr_inserted = np.insert(arr, 1, [5, 6], axis=1)
# [[1 5 2]
#  [3 6 4]]

#eliminar elemento de una posición
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_2d_deleted = np.delete(arr_2d, 1, axis=0)
# [[1 2 3]]

In [ ]:
#ej 4 -> manipular arreglos de forma grupal

#apilar verticalmente (encima del otro)
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr_vstacked = np.vstack((arr1, arr2))
# [[1 2 3]
#  [4 5 6]]

#apilar horizanotalmente
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr_hstacked = np.hstack((arr1, arr2))
#[1 2 3 4 5 6]

#unir en un eje
# Concatenar a lo largo del eje 0 (filas)
arr1 = np.array([[1, 2], 
                 [3, 4]])
arr2 = np.array([[5, 6], 
                 [7, 8]])
result1 = np.concatenate((arr1, arr2), axis=0)
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]

#concateno columnas
arr1 = np.array([[1, 2], 
                 [3, 4]])
arr2 = np.array([[5, 6], 
                 [7, 8]])
result1 = np.concatenate((arr1, arr2), axis=1)
# [[1 2 5 6]  # 1 es la 1er columna de arr1       2  es la 2da columna de arr1         5 es la 1er columna de arr2      etc
#  [3 4 7 8]] # 3                                 4                                    7

In [ ]:
#ej 5-> acceso a arreglos

#así como los arreglos tenían slices eso también lo podemos aplicar a las matrices y arreglos de más dimensiones
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
#(primeras dos filas y primeras dos columnas)
sub_mat = mat[:2, :2]
# [[1 2]
#  [4 5]]

# Pandas
biblioteca pensada para trabajar con datos relacionales o etiquetados

In [25]:
#ej 1
import pandas as pd

data = {
    'Nombre': ['Juan', 'Maria', 'Pedro', 'José'],
    'Edad': [20, 26, 18, 22],
    'Pais': ['Argentina', 'Peru', 'Brasil', 'Chile']
}
df = pd.DataFrame(data)
print(df.columns)
df.info()

Index(['Nombre', 'Edad', 'Pais'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Nombre  4 non-null      object
 1   Edad    4 non-null      int64 
 2   Pais    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes


In [26]:
new_row1 = {"Nombre":"Pablo", "Edad":30, "Pais":"Colombia"}
new_row2 = ["Pablo", 30, "Colombia"]
df.loc[len(df)] = new_row1
df.loc[len(df)] = new_row2
df.head(10)

Nombre  Edad       Pais
0   Juan    20  Argentina
1  Maria    26       Peru
2  Pedro    18     Brasil
3   José    22      Chile
4  Pablo    30   Colombia
5  Pablo    30   Colombia

loc (Label-based Indexing) -> accedo a filas o columnas en base a su nombre

iloc (Integer-location based Indexing) -> accedo con el número del índice, para acceder a filas o columnas
Acceso a las filas en las posiciones 0 hasta 1 (no incluye 2)
print(df.iloc[0:2])

Acceder a la primera columna (índice 0)
columna_0 = df.iloc[:, 0]

In [24]:
#elimino datos duplicados automáticamente
df = df.drop_duplicates()
df.head(10)

Nombre  Edad       Pais
0   Juan    20  Argentina
1  Maria    26       Perú
2  Pedro    18     Brasil
3   José    22      Chile
4  Pablo    30   Colombia

In [31]:
#corrijo los Peru sin acento

for index, row in df.iterrows():
    if row['Pais'] == 'Peru':
        df.loc[index, 'Pais'] = 'Perú'

#otra forma de hacerlo: df['Pais'] = df['Pais'].replace('Peru', 'Perú')
df.head(10)

Nombre  Edad       Pais
0   Juan    20  Argentina
1  Maria    26       Perú
2  Pedro    18     Brasil
3   José    22      Chile
4  Pablo    30   Colombia
5  Pablo    30   Colombia

In [32]:
#ej 2 -> guardo el resultado en diferentes formatos

# Guardar en un archivo con separación por delimitadores (tabulador)
df.to_csv('pra1-pandas-ej2.txt', sep='\t', index=False)

# Guardar en un archivo con separación por delimitadores (punto y coma)
df.to_csv('pra1-pandas-ej2.csv', sep=';', index=False)

# Guardar en un archivo Excel
df.to_excel('pra1-pandas-ej2.xlsx', index=False)

# Guardar en un archivo JSON
df.to_json('pra1-pandas-ej2.json', orient='records', lines=True)