# Métricas
---
###Precision, recall, F1 score y accuracy R2 score

**Definición de funciones para métricas**

In [ ]:
import pandas as pd
import numpy as np

# calcula las metricas precision, recall, f1-score y accuracy a partir de la matriz de confusion
# retorna tupla: ( precision, recall, f1_score, accuracy )
def calcular_metricas(conf_mat):

    # calcula precision por cada clase
    precision = np.zeros(conf_mat.shape[0])
    for i in range(0, len(conf_mat)):
        precision[i] = conf_mat[i][i]/sum(conf_mat.T[i])

    # calcula por cada clase
    recall = np.zeros(conf_mat.shape[0])
    for i in range(0, len(conf_mat)):
        recall[i] = conf_mat[i][i]/sum(conf_mat[i])

    f1_score = 2* (precision*recall) /(precision+recall)

    accuracy =  0
    for i in range(0, len(conf_mat)):
        accuracy+=conf_mat[i][i]
    accuracy/= conf_mat.sum()

    return ( precision, recall, f1_score, accuracy )

# el parámetro metricas es una tupla ( precision, recall, f1_score, accuracy )
def imprimir_metricas( metricas ):
    (precision, recall, f1_score, accuracy) = metricas
    print('\n clase   precision    recall    f1-score')
    for i in range(0, len(precision)):
        print('%5d %10.2f %10.2f %10.2f' % (i, precision[i], recall[i], f1_score[i]))
    print('\naccuracy: %6.2f\n' % accuracy)



**Cálculo e impresión de métricas**

In [ ]:
from sklearn.metrics import confusion_matrix

# Supongamos que tenemos etiquetas reales y predicciones para tres clases
y_true = [0, 1, 2, 0, 2, 1, 2, 0, 2, 1, 2, 0, 1, 2]  # Etiquetas reales
y_pred = [0, 1, 2, 0, 1, 1, 2, 0, 2, 0, 1, 2, 0, 2]  # Predicciones del modelo

confusion = confusion_matrix(y_true, y_pred)
print('\n Matriz de Confusión:')
print(confusion, '\n')

#calcula métricas de forma manual
metricas = calcular_metricas(confusion)
imprimir_metricas(metricas)



 Matriz de Confusión:
[[3 0 1]
 [2 2 0]
 [0 2 4]] 


 clase   precision    recall    f1-score
    0       0.60       0.75       0.67
    1       0.50       0.50       0.50
    2       0.80       0.67       0.73

accuracy:   0.64



In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

################################ calcula todas las métricas separadas ##############################

accuracy = accuracy_score(y_true, y_pred)
print('Precisión (Accuracy): {:.2f}'.format(accuracy))

precision = precision_score(y_true, y_pred, average=None) # precisión (precision) por clase
print('             Precisión por clase:', precision)

recall = recall_score(y_true, y_pred, average=None) # exhaustividad (recall) por clase
print('Exhaustividad (Recall) por clase:', recall)

# F1-score (otros nombre: F1-measure o F-beta score)
f1 = f1_score(y_true, y_pred, average=None) # puntuación F1 por clase
print('         Puntuación F1 por clase:', f1)

################################ calcula todas las métricas juntas #################################
report = classification_report(y_true, y_pred)
print('Resultado de la clasificación:\n%s' % report)

Precisión (Accuracy): 0.64
             Precisión por clase: [0.6 0.5 0.8]
Exhaustividad (Recall) por clase: [0.75       0.5        0.66666667]
         Puntuación F1 por clase: [0.66666667 0.5        0.72727273]
Resultado de la clasificación:
              precision    recall  f1-score   support

           0       0.60      0.75      0.67         4
           1       0.50      0.50      0.50         4
           2       0.80      0.67      0.73         6

    accuracy                           0.64        14
   macro avg       0.63      0.64      0.63        14
weighted avg       0.66      0.64      0.65        14

